/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author osand
 */
public class MainView extends javax.swing.JFrame {

    private static RoomCategoryView roomCategoryView = null;
    private static RoomView roomView = null;
    private static CustomerView customerView = null;
    private static ReservationView reservationView = null;
    
    public MainView() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btRoomManager = new javax.swing.JButton();
        btCustomerManager = new javax.swing.JButton();
        btRoomCategoryManager = new javax.swing.JButton();
        btReservationManager = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        btRoomManager.setText("Room Manager");
        btRoomManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRoomManagerActionPerformed(evt);
            }
        });

        btCustomerManager.setText("Customer Manager");
        btCustomerManager.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btCustomerManagerMouseClicked(evt);
            }
        });
        btCustomerManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCustomerManagerActionPerformed(evt);
            }
        });

        btRoomCategoryManager.setText("Room Category Manager");
        btRoomCategoryManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRoomCategoryManagerActionPerformed(evt);
            }
        });

        btReservationManager.setText("Reservation Manager");
        btReservationManager.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btReservationManagerMouseClicked(evt);
            }
        });
        btReservationManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btReservationManagerActionPerformed(evt);
            }
        });

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 255, 255), null, null));

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel1.setText("Hotel Management System");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(356, 356, 356)
                .addComponent(jLabel1)
                .addContainerGap(302, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/hotel1.png"))); // NOI18N
        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 594, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btReservationManager, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btCustomerManager, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btRoomManager, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btRoomCategoryManager, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(btCustomerManager, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(btReservationManager, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(btRoomManager, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(btRoomCategoryManager, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btRoomManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRoomManagerActionPerformed
        

        
     if(roomView == null || !roomView.isVisible()){
        
        roomView = new RoomView();
        roomView.setVisible(true);
        roomView.setLocationRelativeTo(null);
        
    } else {
        
        roomView.setVisible(true);
        roomView.setLocationRelativeTo(null); 
        
    }
        
                       
        
    }//GEN-LAST:event_btRoomManagerActionPerformed

    private void btCustomerManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCustomerManagerActionPerformed
       
        
        if(customerView == null || !customerView.isVisible()){
        
        customerView = new CustomerView();
        customerView.setVisible(true);
        customerView.setLocationRelativeTo(null);
        
    } else {
        
        customerView.setVisible(true);
        customerView.setLocationRelativeTo(null); 
        
    }
       
             
    }//GEN-LAST:event_btCustomerManagerActionPerformed

    private void btCustomerManagerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btCustomerManagerMouseClicked
         
    }//GEN-LAST:event_btCustomerManagerMouseClicked

    private void btRoomCategoryManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRoomCategoryManagerActionPerformed
       
    if(roomCategoryView == null || !roomCategoryView.isVisible()){
        
        roomCategoryView = new RoomCategoryView();
        roomCategoryView.setVisible(true);
        roomCategoryView.setLocationRelativeTo(null);
        
    } else {
        
        roomCategoryView.setVisible(true);
        roomCategoryView.setLocationRelativeTo(null); 
        
    }
        
    }//GEN-LAST:event_btRoomCategoryManagerActionPerformed

    private void btReservationManagerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btReservationManagerMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btReservationManagerMouseClicked

    private void btReservationManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btReservationManagerActionPerformed
        
  
    if(reservationView == null || !reservationView.isVisible()){
        
        reservationView = new ReservationView();
        reservationView.setVisible(true);
        reservationView.setLocationRelativeTo(null);
        
    } else {
        
        reservationView.setVisible(true);
        reservationView.setLocationRelativeTo(null); 
        
    }
        
    }//GEN-LAST:event_btReservationManagerActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCustomerManager;
    private javax.swing.JButton btReservationManager;
    private javax.swing.JButton btRoomCategoryManager;
    private javax.swing.JButton btRoomManager;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
